config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items do
    member do
      put 'decrement'
    end 
  end

  resources :carts

  get 'store/index'

  resources :products
  root 'store#index'
  match ':controller(/:action/(:id))', :via => [:get, :post, :patch]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.find_by(product_id: product_id)

		if current_item
			current_item.qty += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end 

	def grand_total
		line_items.to_a.sum{ |item| item.total_price }
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:index, :show]
  before_action :find_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    #@cart = @cart
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Invalid Cart #{params[:id]}"
      redirect_to store_index_path, notice: "Invalid Cart"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h2> Partial Cart </h2>

<table class="sidebar_cart">
  <tbody>
    <%= render(@cart.line_items) %>
    <tr>
      <td colspan="3"><h4 style="border-top:1px solid #555;padding-top:10px"> Grand Total : <%= number_to_currency(@cart.grand_total) %></h4></td>
    </tr>
  </tbody>
</table>

<%= button_to "Checkout", new_order_path, method: :get %>

<style type="text/css">
	h2, .sidebar_cart{color:#fff;}
</style>

<script>
	$(function(){
		/*$(".butMinus").on("click", function(e){
			item = $(this).parent('td').next().find('.txtQty');

			if(!isNaN(item.text()))
			{
				if(item.text() == 1){
					item.closest('tr').hide();
					$(".itemDelete").click();
					return false;
				}

				item.text(parseInt(item.text()) - 1);
			}
		});*/
	});
</script>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h2>Listing carts</h2>



<br>

<%= link_to 'New Cart', new_cart_path %>

<style type="text/css">
</style>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<h1> View Cart Summary</h1>

<table>
  <tbody>
    <%= render(@cart.line_items) %>
    <tr>
      <td colspan="3"><h4 style="border-top:1px solid #555;padding-top:10px"> Grand Total : <%= @cart.grand_total %></h4></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>


<style type="text/css">
	h1, table{color:#000;}
</style>