config/routes.rb
Rails.application.routes.draw do
  resources :orders

  resources :line_items do
    member do
      put 'decrement'
    end 
  end

  resources :carts

  get 'store/index'

  resources :products
  root 'store#index'
  match ':controller(/:action/(:id))', :via => [:get, :post, :patch]

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  def total_price
  	product.price * qty
  end

  def self.decrease(li_id)
  	current_li = LineItem.find(li_id)

  	if current_li.qty > 1
  		current_li.qty -= 1
  	else
  		current_li.destroy
  	end
  	current_li
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :show, :decrement]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @prod = Product.find(params[:product_id])
    #@line_item = @cart.line_items.build(product: @prod)
    @line_item = @cart.add_product(@prod.id)
    # test purpuse
    session[:counter] = 0

    #@line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_path }
        format.js {}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement

    @line_item = LineItem.decrease(params[:id])
    #current_li = LineItem.find(params[:id])

    # if current_li.qty == 1 
    #   current_li.destroy
    # else
    #   current_li.qty = current_li.qty - 1
    # end
    
    respond_to do |format|
      if @line_item.save
        format.js {}
        format.html { redirect_to store_index_path }
      else
        format.html{redirect_to store_index_path}
      end
    end

  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(session[:cart_id]), notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end
 

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
      <tr>
      	<td> <%= button_to "-", decrement_line_item_path(line_item), method: :put %> </td>
      	<td> <%= button_to "*", decrement_line_item_path(line_item), method: :put, remote: true %> </td>
        <td><%= content_tag(:div, line_item.qty, class:'txtQty') %> </td>
        <td> X <%= line_item.product.title %> </td>
        <td><%= line_item.total_price %></td>
        <td><%= link_to "Delete", line_item, method: :delete, class: 'itemDelete', style: 'display:none' %></td>
      </tr>


app/views/line_items/create.js.erb
$("#cart").html("<%= j render('carts/cart') %>");

app/views/line_items/decrement.js.erb

$("#cart").html("<%= j render 'carts/cart' %>");

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product.title %></td>
        <td><%= line_item.cart.id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
edx<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product.title %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart.id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>